name: Upload Weather Data to MetOffice's WOW

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)

jobs:
  upload:
    name: Upload Weather Data
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v4

      - name: Install Python
        run: uv python install

      - name: Upload Weather Data
        env:
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          WOW_SITE_ID: ${{ secrets.WOW_SITE_ID }}
          WOW_API_KEY: ${{ secrets.WOW_API_KEY }}
        run: uv run upload
