name: Upload Weather Data to WOW

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run weather script
        env:
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          WOW_SITE_ID: ${{ secrets.WOW_SITE_ID }}
          WOW_API_KEY: ${{ secrets.WOW_API_KEY }}
        run: python weather_to_wow.py